apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mall-gateway
  name: mall-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mall-gateway
  template:
    metadata:
      labels:
        app: mall-gateway
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "mallgateway"
        dapr.io/app-port: "9001"           
    spec:
      containers:
      - image: daprxp.azurecr.io/mall-gateway:v3
        name: mall-gateway
        ports:
        - containerPort: 9001
        env:
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
             name: db-mysql
             key: username
        - name: MYSQL_PWD
          valueFrom:
            secretKeyRef:
             name: db-mysql
             key: password             
        - name: MYSQL_HOST
          valueFrom:
            secretKeyRef:
             name: db-mysql
             key: host                 
        - name: MYSQL_PORT
          valueFrom:
            secretKeyRef:
             name: db-mysql
             key: port                 
        - name: NACOS_HOST
          valueFrom:
            secretKeyRef:
             name: nacos-server
             key: host                     
        - name: NACOS_PORT
          valueFrom:
            secretKeyRef:
             name: nacos-server
             key: port
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: mall-gateway
  name: mall-gateway
spec:
  ports:
  - port: 9001
    protocol: TCP
    targetPort: 9001
  selector:
    app: mall-gateway             
